import { Feed as FeedGen } from 'feed';
import { config } from '../config.js';
import type { Article, Feed } from '../db/schema.js';

export type OutputFormat = 'rss' | 'atom' | 'json';

export function parseFormat(value: string | undefined, fallback: string): OutputFormat {
  if (value === 'rss' || value === 'atom' || value === 'json') return value;
  return (fallback as OutputFormat) ?? 'rss';
}

export interface GeneratedFeed {
  body: string;
  contentType: string;
}

const CONTENT_TYPES: Record<OutputFormat, string> = {
  rss: 'application/rss+xml; charset=utf-8',
  atom: 'application/atom+xml; charset=utf-8',
  json: 'application/feed+json; charset=utf-8',
};

/**
 * Resolves the source publication's homepage, used as the feed's `link` so
 * readers can find the right favicon. Prefers an explicit URL (from the mapped
 * site's domain) and otherwise uses the origin of the first article URL.
 */
function resolveHomepage(articles: Article[], explicit?: string): string | undefined {
  if (explicit) return explicit;
  for (const article of articles) {
    try {
      return new URL(article.url).origin;
    } catch {
      // Skip malformed URLs and try the next article.
    }
  }
  return undefined;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Injects a `<dc:creator>` element into each RSS `<item>`.
 *
 * The `feed` library only emits an RSS `<author>` when both an email and a name
 * are present, and it never emits `<dc:creator>` — the element feed readers
 * (NetNewsWire, Feedbin, …) actually display as the byline. Items are generated
 * in the same order they are added, which matches `articles`, so we inject each
 * article's author into the corresponding item by order. The `dc` namespace is
 * already declared on the `<rss>` root by the library.
 */
function injectRssCreators(xml: string, articles: Article[]): string {
  let index = 0;
  return xml.replace(/<\/item>/g, (closing) => {
    const author = articles[index]?.author;
    index += 1;
    if (!author) return closing;
    return `<dc:creator>${escapeXml(author)}</dc:creator>${closing}`;
  });
}

/** Builds an RSS/Atom/JSON feed document from cached full-text articles. */
export function generateFeed(
  feed: Feed,
  articles: Article[],
  format: OutputFormat,
  options: { homepageUrl?: string } = {},
): GeneratedFeed {
  const selfUrl = `${config.PUBLIC_BASE_URL}/feed/${feed.accessToken}`;
  const updated = articles[0]?.publishedAt ?? feed.lastRefreshedAt ?? new Date();

  // The channel `link` should point at the original publication's homepage, not
  // at this bridge — feed readers (e.g. Feedbin) derive the feed's favicon by
  // crawling that site. Prefer an explicit homepage (from the mapped site), and
  // fall back to the origin of the first article URL.
  const homepage = resolveHomepage(articles, options.homepageUrl) ?? selfUrl;

  const gen = new FeedGen({
    id: selfUrl,
    title: feed.name,
    description: `Full-text feed generated by Full-Text RSS Bridge for ${feed.name}`,
    link: homepage,
    // Best-effort icon for Atom (<icon>) and JSON Feed (favicon); RSS readers
    // discover the favicon by crawling `link` above.
    favicon: homepage !== selfUrl ? `${homepage}/favicon.ico` : undefined,
    updated,
    copyright: `© ${new Date().getFullYear()} original publishers`,
    generator: 'full-text-rss-bridge',
    feedLinks: {
      rss: `${selfUrl}.rss`,
      atom: `${selfUrl}.atom`,
      json: `${selfUrl}.json`,
    },
  });

  for (const article of articles) {
    gen.addItem({
      title: article.title ?? '(untitled)',
      id: article.guid,
      link: article.url,
      date: article.publishedAt ?? article.fetchedAt ?? article.createdAt,
      content: article.contentHtml ?? undefined,
      description: article.summary ?? undefined,
      author: article.author ? [{ name: article.author }] : undefined,
    });
  }

  let body: string;
  if (format === 'atom') body = gen.atom1();
  else if (format === 'json') body = gen.json1();
  else body = injectRssCreators(gen.rss2(), articles);

  return { body, contentType: CONTENT_TYPES[format] };
}
