import { Feed as FeedGen } from 'feed';
import { config } from '../config.js';
import type { Article, Feed } from '../db/schema.js';

export type OutputFormat = 'rss' | 'atom' | 'json';

export function parseFormat(value: string | undefined, fallback: string): OutputFormat {
  if (value === 'rss' || value === 'atom' || value === 'json') return value;
  return (fallback as OutputFormat) ?? 'rss';
}

export interface GeneratedFeed {
  body: string;
  contentType: string;
}

const CONTENT_TYPES: Record<OutputFormat, string> = {
  rss: 'application/rss+xml; charset=utf-8',
  atom: 'application/atom+xml; charset=utf-8',
  json: 'application/feed+json; charset=utf-8',
};

/** Builds an RSS/Atom/JSON feed document from cached full-text articles. */
export function generateFeed(
  feed: Feed,
  articles: Article[],
  format: OutputFormat,
): GeneratedFeed {
  const selfUrl = `${config.PUBLIC_BASE_URL}/feed/${feed.accessToken}`;
  const updated = articles[0]?.publishedAt ?? feed.lastRefreshedAt ?? new Date();

  const gen = new FeedGen({
    id: selfUrl,
    title: feed.name,
    description: `Full-text feed generated by Full-Text RSS Bridge for ${feed.name}`,
    link: selfUrl,
    updated,
    copyright: `© ${new Date().getFullYear()} original publishers`,
    generator: 'full-text-rss-bridge',
    feedLinks: {
      rss: `${selfUrl}.rss`,
      atom: `${selfUrl}.atom`,
      json: `${selfUrl}.json`,
    },
  });

  for (const article of articles) {
    gen.addItem({
      title: article.title ?? '(untitled)',
      id: article.guid,
      link: article.url,
      date: article.publishedAt ?? article.fetchedAt ?? article.createdAt,
      content: article.contentHtml ?? undefined,
      description: article.summary ?? undefined,
      author: article.author ? [{ name: article.author }] : undefined,
    });
  }

  let body: string;
  if (format === 'atom') body = gen.atom1();
  else if (format === 'json') body = gen.json1();
  else body = gen.rss2();

  return { body, contentType: CONTENT_TYPES[format] };
}
